spring.application.name=Ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/North_Wind
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto =update
spring.jpa.show-sql=true

server.port = 8080

secretJwtString = mannishness123456789mannishness123456789



